#ifndef _configDefaultDvb_H_
#define _configDefaultDvb_H_

#include "solution.h"
#ifndef DEFAULT_DVB_CHANNEL_MANAGE_FLAG
#define DEFAULT_DVB_CHANNEL_MANAGE_FLAG 0
#endif

#ifndef DEFAULT_DVB_SERVICE_CHECK
#define DEFAULT_DVB_SERVICE_CHECK 900
#endif

#define DEFAULT_LNB_CONNECT_TYPE 0
#define DEFAULT_LOCAL_LONGITUDE ""
#define DEFAULT_LOCAL_LATITUDE ""
#define DEFAULT_MAIN_FREQUENCY 10759000
#define DEFAULT_MAIN_SYMBOLRATE 30000
#define DEFAULT_MAIN_POLARIZATION 0
#define DEFAULT_SATELLITE_LONGITUDE ""
#define DEFAULT_REVISE_SWITCH 0
#define DEFAULT_LAST_CHANNELTYPE 0
#define DEFAULT_LAST_VIDEO_NUMBER -1
#define DEFAULT_LAST_AUDIO_NUMBER -1

#endif // _configDefaultDvb_H_
