#ifndef _configDefaultApp_H_
#define _configDefaultApp_H_

#ifndef DEFAULT_TIME_ZONE
#endif

#ifndef DEFAULT_NTP
#endif

#ifndef DEFAULT_NTP1
#endif

#ifndef DEFAULT_STB_SOFT_TYPE
#define DEFAULT_STB_SOFT_TYPE "A"
#endif

#ifndef DEFAULT_EDS
#endif

#ifndef DEFAULT_EDS1
#endif

#ifndef DEFAULT_LANG
#endif

#ifndef DEFAULT_PAGE_WIDTH
#endif

#ifndef DEFAULT_PAGE_HEIGHT
#endif

#ifndef DEFAULT_STB_BINDTYPE
#endif

#ifndef DEFAULT_REBOOT_TIME
#endif

#ifndef DEFAULT_GOTO_MENU
#define DEFAULT_GOTO_MENU 0
#endif

#ifndef DEFAULT_AUTO_STANDBY_MODE
#define DEFAULT_AUTO_STANDBY_MODE 0
#endif

#ifndef DEFAULT_AUTO_STANDBY_TIME
#define DEFAULT_AUTO_STANDBY_TIME 0
#endif

/*************************** customer ********************************/

#ifndef DEFAULT_NTV_USER
#endif

#ifndef DEFAULT_NTV_PASSWD
#endif

#ifndef DEFAULT_NTV_AES_PASSWD
#define DEFAULT_NTV_AES_PASSWD ""
#endif

#ifndef DEFAULT_DEF_CONT_ACC
#define DEFAULT_DEF_CONT_ACC ""
#endif

#ifndef DEFAULT_DEF_CONT_PWD
#define DEFAULT_DEF_CONT_PWD ""
#endif

#ifndef DEFAULT_DEF_AES_CONT_PWD
#define DEFAULT_DEF_AES_CONT_PWD ""
#endif

#ifndef DEFAULT_AUTH_SHOW_PIC_FLAG
#define DEFAULT_AUTH_SHOW_PIC_FLAG SWITCH_ON
#endif

#ifndef DEFAULT_BOOT_PIC_ENABLE_FLAG
#define DEFAULT_BOOT_PIC_ENABLE_FLAG SWITCH_ON
#endif

#ifndef DEFAULT_START_PIC_ENABLE_FLAG
#define DEFAULT_START_PIC_ENABLE_FLAG SWITCH_ON
#endif

#ifndef DEFAULT_TOP_MAGIN
#endif

#ifndef DEFAULT_BOTTOM_MAGIN
#endif

#ifndef DEFAULT_LEFT_MAGIN
#endif

#ifndef DEFAULT_RIGHT_MAGIN
#endif

#ifndef DEFAULT_STB_NAME
#endif

#ifndef DEFAULT_PADIRETRYINTERVAL
#define DEFAULT_PADIRETRYINTERVAL 10
#endif

#ifndef DEFAULT_LCPRETRYTIME
#define DEFAULT_LCPRETRYTIME 6
#endif

#ifndef DEFAULT_LCPRETRYINTERVAL
#define DEFAULT_LCPRETRYINTERVAL 30
#endif

#ifndef DEFAULT_DHCPRETRYINTERVAL
#define DEFAULT_DHCPRETRYINTERVAL 30
#endif

#ifndef DEFAULT_LINKPROBETIME
#define DEFAULT_LINKPROBETIME 12
#endif

#ifndef DEFAULT_STARTUPCAPTURE
#endif

//0:IPTV 1:OTT 2:IPTV & OTT.
#ifndef DEFAULT_USERFIELD
#define DEFAULT_USERFIELD 2
#endif

#ifndef DEFAULT_NETCHECK_MULTICASTADD
#define DEFAULT_NETCHECK_MULTICASTADD  "224.1.1.1"
#endif

#ifndef DEFAULT_NETCHECK_MULTICASTPORT
#define DEFAULT_NETCHECK_MULTICASTPORT  1111
#endif

#ifndef DEFAULT_NETCHECK_MULTICASTSOURCEADD
#define DEFAULT_NETCHECK_MULTICASTSOURCEADD  "10.10.10.6"
#endif

#ifndef DEFAULT_NETCHECK_DOMAIN
#define DEFAULT_NETCHECK_DOMAIN  "eds.t2.iptv.gd.cn"
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTDOMAIN
#define DEFAULT_NETCHECK_PINGTESTDOMAIN  "iTV.zj.vnet.cn"
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTIP
#define DEFAULT_NETCHECK_PINGTESTIP  "127.0.0.1"
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTSIZE
#define DEFAULT_NETCHECK_PINGTESTSIZE  32
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTTIMEOUT
#define DEFAULT_NETCHECK_PINGTESTTIMEOUT  4000
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTCOUNT
#define DEFAULT_NETCHECK_PINGTESTCOUNT  4
#endif

#ifndef DEFAULT_NETCHECK_PINGTESTTTL
#define DEFAULT_NETCHECK_PINGTESTTTL  255
#endif

#endif // _configDefaultApp_H_
