#ifndef _configDefaultTr069_H_
#define _configDefaultTr069_H_

#ifndef DEFAULT_TR069_ENABLE
#endif

#ifndef DEFAULT_TR069_UPGRADES
#endif

#ifndef DEFAULT_TR069_TYPE
#if defined(INCLUDE_TR069_CTC)
    #define DEFAULT_TR069_TYPE 1
#elif defined(INCLUDE_TR069_CU)
    #define DEFAULT_TR069_TYPE 2
#else
    #define DEFAULT_TR069_TYPE 0
#endif
#endif
#ifdef INCLUDE_HMWMGMT

#ifndef DEFAULT_TR069_FIRSTUSEDATE 
#define DEFAULT_TR069_FIRSTUSEDATE 0
#endif

#ifndef DEFAULT_TR069_URL
// #define DEFAULT_TR069_URL "http://110.1.1.183:37021/acs"
#endif

#ifndef DEFAULT_TR069_URLBACKUP
#define DEFAULT_TR069_URLBACKUP ""
#endif

#ifndef DEFAULT_TR069_USERNAME
#define DEFAULT_TR069_USERNAME "testcpe"
#endif

#ifndef DEFAULT_TR069_PASSWORD
#define DEFAULT_TR069_PASSWORD "ac5entry"
#endif 

#ifndef DEFAULT_TR069_URLMODIFYFLAY
#define DEFAULT_TR069_URLMODIFYFLAY 15
#endif 

#ifndef DEFAULT_TR069_INFORMENABLE
#define DEFAULT_TR069_INFORMENABLE 1
#endif

#ifndef DEFAULT_TR069_INFORINTERVAL
#define DEFAULT_TR069_INFORINTERVAL 3600
#endif

#ifndef DEFAULT_TR069_CONNECTIONREQUESETUSERNAME
#define DEFAULT_TR069_CONNECTIONREQUESETUSERNAME "admin"
#endif

#ifndef DEFAULT_TR069_CONNECTIONREQUESETPASSWORD
#define DEFAULT_TR069_CONNECTIONREQUESETPASSWORD "admin"
#endif

#ifndef DEFAULT_TR069_STUNEABLE
#define DEFAULT_TR069_STUNEABLE 0
#endif 

#ifndef DEFAULT_TR069_CONNECTIONREQUESTPATH
#define DEFAULT_TR069_CONNECTIONREQUESTPATH "/cpe"
#endif 

#ifndef DEFAULT_TR069_STUNMAXALIVEPERIOD
#define DEFAULT_TR069_STUNMAXALIVEPERIOD 170
#endif

#ifndef DEFAULT_TR069_STUNMINALIVEPERIOD
#define DEFAULT_TR069_STUNMINALIVEPERIOD 170
#endif

#endif

#endif // _configDefaultTr069_H_
