#ifndef _pathConfig_H_
#define _pathConfig_H_

#include "pathDefine.h"

#if defined(ANDROID)

#ifndef ANDROID_PACKAGE_NAME
#error "android_package_name not defined."
#endif

#ifndef CONFIG_FILE_DIR
#define CONFIG_FILE_DIR "/data/data/" ANDROID_PACKAGE_NAME "/files"
#endif

#ifndef SYSTEM_LOGO_DIR
#define SYSTEM_LOGO_DIR "/data/data/" ANDROID_PACKAGE_NAME "/files"
#endif

#ifndef CONFIG_UI_DATA_FILE
#define CONFIG_UI_DATA_FILE "/data/data/" ANDROID_PACKAGE_NAME "/files/xbrowser.dat"
#endif

#ifndef DEFAULT_FLASH_DATAPATH
#define DEFAULT_FLASH_DATAPATH "/data/data/" ANDROID_PACKAGE_NAME "/files"
#endif

#ifndef SYS_IMG_PATH_ROOT
#define SYS_IMG_PATH_ROOT "/data/data/" ANDROID_PACKAGE_NAME "/files/sys_images"
#endif

#else
#ifndef CONFIG_FILE_DIR
#define CONFIG_FILE_DIR "/root"
#endif

#ifndef SYSTEM_LOGO_DIR
#define SYSTEM_LOGO_DIR "/root"
#endif

#ifndef SYS_IMG_PATH_ROOT
#define SYS_IMG_PATH_ROOT "/home/hybroad/share/sys_images"
#endif
#endif // defined(ANDROID)

#ifndef DEFAULT_RESOURCE_DATAPATH
#define DEFAULT_RESOURCE_DATAPATH "/home/hybroad/share"
#endif

#ifndef CONFIG_UI_DATA_FILE
#define CONFIG_UI_DATA_FILE	DEFAULT_RESOURCE_DATAPATH"/xbrowser.dat"
#endif

#ifndef DEFAULT_EXTERNAL_DATAPATH
#define DEFAULT_EXTERNAL_DATAPATH "/mnt/usb1"
#endif

#ifndef DEFAULT_DEBUG_DATAPATH
#define DEFAULT_DEBUG_DATAPATH "/mnt/nfs"
#endif

#ifndef DEFAULT_FLASH_DATAPATH
#define DEFAULT_FLASH_DATAPATH "/root"
#endif

#ifndef DEFAULT_RAM_DATAPATH
#define DEFAULT_RAM_DATAPATH "/var"
#endif

#ifndef DEFAULT_PIPE_DATAPATH
#define DEFAULT_PIPE_DATAPATH DEFAULT_RAM_DATAPATH"/pipe"
#endif

#ifndef DEFAULT_TEMP_DATAPATH
#define DEFAULT_TEMP_DATAPATH DEFAULT_FLASH_DATAPATH"/temp"
#endif

#ifndef DEFAULT_JVM_DATAPATH
#define DEFAULT_JVM_DATAPATH DEFAULT_FLASH_DATAPATH"/jvm"
#endif

#ifndef DEFAULT_TEMPLATE_DATAPTH
#define DEFAULT_TEMPLATE_DATAPTH DEFAULT_FLASH_DATAPATH"/template"
#endif

#ifndef DEFAULT_MODULE_DATAPATH
#define DEFAULT_MODULE_DATAPATH DEFAULT_FLASH_DATAPATH"/module"
#endif

#ifndef DEFAULT_MODULE_PRESSURE_DATAPATH
#define DEFAULT_MODULE_PRESSURE_DATAPATH DEFAULT_MODULE_DATAPATH"/pressure"
#endif

#ifndef DEFAULT_MODULE_QOS_DATAPATH
#define DEFAULT_MODULE_QOS_DATAPATH DEFAULT_MODULE_DATAPATH"/qos"
#endif

#ifndef DEFAULT_MODULE_WIFI_DATAPATH
#define DEFAULT_MODULE_WIFI_DATAPATH DEFAULT_MODULE_DATAPATH"/wifi"
#endif

#ifndef DEFAULT_MODULE_CPVR_DATAPATH
#define DEFAULT_MODULE_CPVR_DATAPATH DEFAULT_MODULE_DATAPATH"/cpvr"
#endif

#ifndef DEFAULT_MODULE_FCC_DATAPATH
#define DEFAULT_MODULE_FCC_DATAPATH DEFAULT_MODULE_DATAPATH"/fcc"
#endif

#ifndef DEFAULT_MODULE_VMCA_DATAPATH
#define DEFAULT_MODULE_VMCA_DATAPATH DEFAULT_MODULE_DATAPATH"/vmca"
#endif

#ifndef DEFAULT_MODULE_BT_DATAPATH
#define DEFAULT_MODULE_BT_DATAPATH DEFAULT_MODULE_DATAPATH"/bluetooth"
#endif

#ifndef DEFAULT_MODULE_TR069_DATAPTH
#define DEFAULT_MODULE_TR069_DATAPTH DEFAULT_MODULE_DATAPATH"/tr069"
#endif

#ifndef DEFAULT_MODULE_PAY_DATAPATH
#define DEFAULT_MODULE_PAY_DATAPATH DEFAULT_MODULE_DATAPATH"/pay"
#endif

#ifndef DEFAULT_PAY_SHELL_PUBKEY_PATH
#define DEFAULT_PAY_SHELL_PUBKEY_PATH DEFAULT_MODULE_PAY_DATAPATH"/iptvpub.pem"
#endif

#ifndef DEFAULT_MODULE_CLOUD_DATAPATH
#define DEFAULT_MODULE_CLOUD_DATAPATH DEFAULT_MODULE_DATAPATH"/cloud"
#endif

#ifndef DEFAULT_MODULE_DVB_DATAPATH
#define DEFAULT_MODULE_DVB_DATAPATH DEFAULT_MODULE_DATAPATH"/dvb"
#endif

#ifndef DEFAULT_MODULE_CERTUS_DATAPATH
#define DEFAULT_MODULE_CERTUS_DATAPATH DEFAULT_MODULE_DATAPATH"/certus"
#endif

#endif /* _pathConfig_H_ */
